# Generated by Django 6.0.6 on 2026-06-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PyqApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pyq',
            name='year',
            field=models.CharField(max_length=10),
        ),
    ]
