# Generated by Django 6.0.6 on 2026-07-14 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PyqApp', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='pyq',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='papers/'),
        ),
        migrations.AlterField(
            model_name='pyq',
            name='drive_link',
            field=models.URLField(blank=True),
        ),
    ]
